CPPFLAGS := -O3

TARGETS := xor128_bit xor128_linearity xor128_poor xorshift128plus_32 xorshift128plus_32_test xoroshiro128plus_32 xoroshiro128plus_32_test

.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	$(RM) $(TARGETS)
